### ISSUE TITLE
Question: How can you install oxwiki

### ISSUE THREAD

**Issue by ghost** [SongPhi/oxwiki#1]
Hello Developer,
I have now discovered this plugin and the installation was not successful. I have uploaded the zip package in the backend of Oxwall and created a page called / wiki and linked in the menu. However, when I go to the frontend / wiki to me it will be displayed:

```
DokuWiki Setup Error
The datadir ('pages') at /www /htdocs/xxxxxxxx/social-network/ow_pluginfiles/oxwiki- master/data/pages is not found, is not accessible or writable. You Should Check Your config and permission settings. Or maybe you want to run the Installer?
```

Are you somewhere before an installation guide for Oxwiki? I know you're there and develop interests me only :)

Thanks in advance.

**Comment by thaolt** [comment]
Hi AlexL777,

Thank you for your interested in Oxwiki plugin. As stated, it's still in very early state of development and meant for developers. So there is not yet an installer. However it is not too hard to get it up and running manually, please follow below steps:
- First please uninstall and delete current oxwiki on your site. (oxwiki-master/ is a wrong path)
- Download the master zip file to your computer
- Extract it
- create a new folder named "oxwiki"
- move all extracted files into newly created folder.
- then right click the new folder of "oxwiki", zip it again, it should be named oxwiki.zip
- Then upload and install to your testing site.
- You have to have hosting file manager or FTP access (filezilla) to do following steps
- Navigate to /social-network/ow_pluginfiles/
- Create "oxwiki" folder
- Upload/copy "data" folder from extracted master zip / dokuwiki/data into /social-network/ow_pluginfiles/oxwiki/
- It should look like: /social-network/ow_pluginfiles/oxwiki/data/security.png
- Then you are good to go to add new plugin and install it again

I hope this would be helpful. Good luck.

Regards,
Thao

**Comment by ghost** [comment]
Thank you for your detailed description and I'm doing something I nor false. If one is then in wiki /social_network/wiki, then it does not look like DokuWiki design from CSS as if missing.
Can you do it yourself here (http://wpzweinull.ch/social-network/wiki#sthash.Xmzx1rkh.dpbs) View again.

Otherwise, I have installed it according to your instructions. Maybe I did something not observed. For a tip, I would be very grateful.

![oxwall-dokuwiki-errors](https://cloud.githubusercontent.com/assets/7885632/10484433/50de4138-7285-11e5-82ea-673ddd800a59.jpg)

**Comment by thaolt** [comment]
Hi, it's a bug, you could fix it by edit ow_plugins/oxwiki/dokuwiki/conf/dokuwiki.php (line 24)
It should be

```
$conf['basedir']     = '/';
```

Save and then refresh your wiki page 2 times ( and/or with Ctrl+F5 )

Please let me know if it would solve css issue for you. 
BTW, the plugin is in experimental stage, avoid using it in your production website. As authentication integration is not yet implement. The wiki page is unavoidable visible to everyone, unless your website is for public.

**Comment by ghost** [comment]
Hi,
Thanks for the hints. Then I disabled the plugin for the first time, because it really is so that anyone can change the wiki page and edit online.

I'll wait until it is available to users an official version of this plugin. But otherwise your tip helped with CSS and the DokuWiki page then looked normal.

**Comment by thaolt** [comment]
I'm glad to heard it's working as it should, and yes it's still undone product. Will notified you when a public release come out. Im closing this issue now .
